### ISSUE TITLE
[3dROIstats]: ">" flag not working correctly

### ISSUE THREAD

**Issue by birajstha** [childmindresearch/niwrap#181]
### Package

AFNI

### Tool Name

3dROIstats

### Problem Description

1. the `>` flag needed for `out_file` is not working correctly. Its generated inside `' '` like below.
```
3dROIstats -1Dformat 
-mask /styx_input/0/ref_bold_corrected_brain_mask_maths_mask.nii.gz 
/styx_input/1/sub-PA001_ses-V1W1_task-facesmatching_run-1_bold_resample_calc_tshift.nii.gz 
'>' desc-roi_stats.1D
```

2. This one may not be an issue but I am adding it here 
When using the function `v_3d_roistats` from `niwrap.afni`, the `format1D` id'ed argument is renamed to `format1_d`.
```
    out = afni.v_3d_roistats(format1_d=True,
                            mask=mask_image,
                            in_file=input_image,
                            out_file="desc-roi_stats.1D")
```
This made me stuck there for few seconds as I was expecting `format1D` as described in its Boutiques Schema below
```
    {
      "id": "format1D",
      "name": "Format1d",
      "type": "Flag",
      "value-key": "[FORMAT1D]",
      "command-line-flag": "-1Dformat",
      "description": "Output results in a 1d format that includes commented labels.",
      "optional": true
    },
```

### Steps to Reproduce

Try generating the following command
```
    3dROIstats -1Dformat 
    -mask mask.nii.gz 
    input_image.nii.gz 
    > sub-PA001_ses-V1W1_task-facesmatching_run-1_bold_resample_calc_tshift_roistat.1D
```

**Comment by kaitj** [comment]
@nx10, does the `>` need to be in the command-line flag or can it go in the template?

```yaml
  "output-files": [
    {
      "name": "Out file",
      "id": "out_file",
      "optional": true,
      "description": "Output file.",
      "path-template": "[IN_FILE]_roistat.1D",
      "value-key": "[OUT_FILE]",
      "command-line-flag": ">"
    },
```

Also, just noticed in the descriptor, `nipype-interface` needs to be removed.
